@startuml

actor "Внешняя система" as client
participant "Платформа\nPluginPlatform" as platform
collections "Реестр плагинов\nPluginPlatform" as registry
control "Загрузчик плагинов\nPluginLoader" as loader
entity "Плагин" as plugin

title Схема работы

client -> platform : Отправка запроса
activate platform

platform -> registry: Поиск плагина в кеше
activate registry
alt Плагин не найден в кеше
    registry -> registry: Поиск настроек плагина\nPluginConfig
    registry <-> loader: Загрузка плагина в кеш
end
return Сконфигурированный плагин

platform -> plugin : Запуск задачи
activate plugin
    plugin -> plugin : Выполнение
return Результат задачи

return Результат выполнения плагина

@enduml
