server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      min: ${HTTP_MIN_THREADS:10}
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:300}

spring:
  application:
    name: plugin-platform
  main:
    allow-bean-definition-overriding: true

logging:
  config: "classpath:logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  server:
    port: ${MANAGMENT_SERVER_PORT:88} # Выносим actuator на отдельный порт

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    supportedSubmitMethods: ${SWAGGER_OPERATIONS:"get", "post"}
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}

custom:
  plugins:
    plugins-folder: ${PLUGIN_FOLDER:C:\plugins\}
    classes:
      first: "dev.alnat.plugin_platform.plugin.plugins.FirstPlugin"
      second: "dev.alnat.plugin_platform.plugin.plugins.SecondPlugin"
