server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      min: ${HTTP_MIN_THREADS:10}
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:300}
      acceptors: ${JETTY_ACCEPTORS_COUNT:1}
      selectors: ${JETTY_SELECTORS_COUNT:1}

spring:
  application:
    name: plugin-platform
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  server:
    port: ${MANAGMENT_SERVER_PORT:88}

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    supportedSubmitMethods: ${SWAGGER_OPERATIONS:"get", "post"}
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}

custom:
  plugins:
    plugins-folder: ${PLUGIN_FOLDER:C:\plugins\example_plugins.jar}